import{a as m,i as a,S as g}from"./assets/vendor-ZlulHAcp.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&n(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const y="49113613-79f6fca50dc45b87a79142d8e",h="https://pixabay.com/api/";async function b(i){try{const r=await m.get(h,{params:{key:y,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0}});if(r.data.hits.length===0)throw new Error("No images found");return r.data}catch(r){return console.error("Error fetching images:",r),null}}const f=document.querySelector(".gallery");let c;function E(i){if(i.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}const r=i.map(({webformatURL:o,largeImageURL:n,tags:e,likes:t,views:s,comments:p,downloads:d})=>`
        <a class="gallery-item" href="${n}">
          <img class="gallery-image" src="${o}" alt="${e}" />
          <div class="info">
            <p><b>Likes</b> ${t}</p>
            <p><b>Views</b> ${s}</p>
            <p><b>Comments</b> ${p}</p>
            <p><b>Downloads</b> ${d}</p>
          </div>
        </a>
      `).join("");console.log(r),f.innerHTML=r,c?c.refresh():c=new g(".gallery a")}function L(){f.innerHTML=""}const q=document.querySelector(".search-form"),l=document.querySelector('input[name="searchQuery"]'),u=document.querySelector(".loading-text");q.addEventListener("submit",async i=>{i.preventDefault();const r=l.value.trim();if(!r){a.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}L(),u.style.display="block";try{const o=await b(r);if(!o||o.hits.length===0){a.error({title:"Error",message:"No images found!",position:"topRight"});return}E(o.hits)}catch(o){console.error("Error:",o),a.error({title:"Error",message:"An error occurred. Please try again later.",position:"topRight"})}finally{u.style.display="none"}l.value=""});
//# sourceMappingURL=index.js.map
